-- MySQL Script generated by MySQL Workbench
-- Tue Nov  6 05:46:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inter` ;
USE `inter` ;

-- -----------------------------------------------------
-- Table `inter`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombrerol` VARCHAR(45) NULL,
  `activorol` TINYINT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `papellido` VARCHAR(45) NULL,
  `sapellido` VARCHAR(45) NULL,
  `ci` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `activo` TINYINT NULL,
  `rol_id_rol` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `ci_UNIQUE` (`ci` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_persona_rol1_idx` (`rol_id_rol` ASC),
  CONSTRAINT `fk_persona_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `activousuario` TINYINT NULL,
  `fechacreacion` DATETIME NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `persona_id_persona`),
  INDEX `fk_usuario_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`funcionalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`funcionalidad` (
  `id_funcionalidad` INT NOT NULL AUTO_INCREMENT,
  `nombrefuncionalidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_funcionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`privilegios` (
  `rol_id_rol` INT NOT NULL,
  `funcionalidad_id_funcionalidad` INT NOT NULL,
  INDEX `fk_privilegios_rol1_idx` (`rol_id_rol` ASC),
  INDEX `fk_privilegios_funcionalidad1_idx` (`funcionalidad_id_funcionalidad` ASC),
  CONSTRAINT `fk_privilegios_rol1`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_privilegios_funcionalidad1`
    FOREIGN KEY (`funcionalidad_id_funcionalidad`)
    REFERENCES `inter`.`funcionalidad` (`id_funcionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`cuenta` (
  `rol_id_rol` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  INDEX `fk_cuenta_rol_idx` (`rol_id_rol` ASC),
  INDEX `fk_cuenta_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_cuenta_rol`
    FOREIGN KEY (`rol_id_rol`)
    REFERENCES `inter`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cuenta_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `inter`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`estudiante` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `activoestudiante` TINYINT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`, `persona_id_persona`),
  INDEX `fk_estudiante_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_estudiante_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombrecarrera` VARCHAR(45) NULL,
  `modalidad` VARCHAR(45) NULL,
  `version` INT NULL,
  `activocarrera` TINYINT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`estudia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`estudia` (
  `estudiante_id_estudiante` INT NOT NULL,
  `estudiante_persona_id_persona` INT NOT NULL,
  `carrera_id_carrera` INT NOT NULL,
  INDEX `fk_estudia_estudiante1_idx` (`estudiante_id_estudiante` ASC, `estudiante_persona_id_persona` ASC),
  INDEX `fk_estudia_carrera1_idx` (`carrera_id_carrera` ASC),
  CONSTRAINT `fk_estudia_estudiante1`
    FOREIGN KEY (`estudiante_id_estudiante` , `estudiante_persona_id_persona`)
    REFERENCES `inter`.`estudiante` (`id_estudiante` , `persona_id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudia_carrera1`
    FOREIGN KEY (`carrera_id_carrera`)
    REFERENCES `inter`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `activoempleado` TINYINT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_empleado_persona1_idx` (`persona_id_persona` ASC),
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `inter`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombreempresa` VARCHAR(45) NULL,
  `direccionempresa` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `nombrerep` VARCHAR(45) NULL,
  `apellidorep` VARCHAR(45) NULL,
  `celular` INT NULL,
  `activoempresa` TINYINT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`asignatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `nombreasignatura` VARCHAR(45) NULL,
  `nivel` INT NULL,
  `descripcionasig` VARCHAR(500) NULL,
  `activoasignatura` TINYINT NULL,
  PRIMARY KEY (`id_asignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`pasantia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`pasantia` (
  `id_pasantia` INT NOT NULL AUTO_INCREMENT,
  `fechainicio` DATE NULL,
  `fechafin` DATE NULL,
  `gestion` VARCHAR(15) NULL,
  `docs` VARCHAR(100) NULL,
  `estadopasantia` INT NULL,
  `empleado_id_empleado` INT NOT NULL,
  `empresa_id_empresa` INT NOT NULL,
  `asignatura_id_asignatura` INT NOT NULL,
  `area` VARCHAR(45) NULL,
  `funciones` VARCHAR(100) NULL,
  `estudiante_id_estudiante` INT NOT NULL,
  `fechavisita` DATE NULL,
  `observacionvisita` VARCHAR(450) NULL,
  `latitud` FLOAT(10,6) NULL,
  `longitud` FLOAT(10,6) NULL,
  `notasupervisor` FLOAT NULL,
  `notatutor` FLOAT NULL,
  `notafinal` FLOAT NULL,
  `observacionp` VARCHAR(45) NULL,
  `activopasantia` TINYINT NULL,
  PRIMARY KEY (`id_pasantia`),
  INDEX `fk_pasantia_empleado1_idx` (`empleado_id_empleado` ASC),
  INDEX `fk_pasantia_empresa1_idx` (`empresa_id_empresa` ASC),
  INDEX `fk_pasantia_asignatura1_idx` (`asignatura_id_asignatura` ASC),
  INDEX `fk_pasantia_estudiante1_idx` (`estudiante_id_estudiante` ASC),
  CONSTRAINT `fk_pasantia_empleado1`
    FOREIGN KEY (`empleado_id_empleado`)
    REFERENCES `inter`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasantia_empresa1`
    FOREIGN KEY (`empresa_id_empresa`)
    REFERENCES `inter`.`empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasantia_asignatura1`
    FOREIGN KEY (`asignatura_id_asignatura`)
    REFERENCES `inter`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pasantia_estudiante1`
    FOREIGN KEY (`estudiante_id_estudiante`)
    REFERENCES `inter`.`estudiante` (`id_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`documentacion` (
  `id_documentacion` INT NOT NULL AUTO_INCREMENT,
  `nombredoc` VARCHAR(100) NULL,
  `fechaentrega` DATE NULL,
  `respaldo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_documentacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`entrega` (
  `documentacion_id_documentacion` INT NOT NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  INDEX `fk_entrega_documentacion1_idx` (`documentacion_id_documentacion` ASC),
  INDEX `fk_entrega_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_entrega_documentacion1`
    FOREIGN KEY (`documentacion_id_documentacion`)
    REFERENCES `inter`.`documentacion` (`id_documentacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`cuadernillo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`cuadernillo` (
  `id_cuadernillo` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NULL,
  `fecha` DATE NULL,
  `decripcion` VARCHAR(10000) NULL,
  `numero_semana` INT NULL,
  PRIMARY KEY (`id_cuadernillo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`union`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`union` (
  `cuadernillo_id_cuadernillo` INT NOT NULL,
  `pasantia_id_pasantia` INT NOT NULL,
  INDEX `fk_union_cuadernillo1_idx` (`cuadernillo_id_cuadernillo` ASC),
  INDEX `fk_union_pasantia1_idx` (`pasantia_id_pasantia` ASC),
  CONSTRAINT `fk_union_cuadernillo1`
    FOREIGN KEY (`cuadernillo_id_cuadernillo`)
    REFERENCES `inter`.`cuadernillo` (`id_cuadernillo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_union_pasantia1`
    FOREIGN KEY (`pasantia_id_pasantia`)
    REFERENCES `inter`.`pasantia` (`id_pasantia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inter`.`requisitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inter`.`requisitos` (
  `id_requisitos` INT NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) NULL,
  `descripcionre` VARCHAR(500) NULL,
  `activorequisito` TINYINT(4) NULL,
  PRIMARY KEY (`id_requisitos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
